### ISSUE TITLE
Error (can someone please help me) when running IPA

### ISSUE THREAD

**Issue by Issarays** [nike4613/BeatSaber-IPA-Reloaded#23]
ERROR: Oops! This should not have happened.

System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Steam\steamapps\common\Beat Saber\Beat Saber_Data\Managed\System.Runtime.Serialization.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName, Boolean overwrite)
   at IPA.Patcher.BackupUnit.Restore()
   at IPA.Patcher.BackupManager.Restore(PatchContext context)
   at IPA.Program.Install(PatchContext context)
[Press any key to continue]

**Comment by nike4613** [comment]
You likely have the game open, otherwise the user you are running IPA.exe as does not have permissions to modify the directory.

**Comment by nike4613** [comment]
Closed for lack of updates after 10 days.
